export const actionTypes = {
    FETCH_START: 'FETCH_START',
    FETCH_SUCCESS: 'FETCH_SUCCESS',
    FETCH_ERROR: 'FETCH_ERROR',
    CHANGE_INPUT: 'CHANGE_INPUT',
    CHANGE_CHECK: 'CHANGE_CHECK',
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT'

}